Translate october blog post to french
lmcnulty/aiid pull request #14
Opened 2022-11-15 19:25 UTC by clari182

2022-11-15 20:42 UTC, lmcnulty requested changes
Merci :)

I found a few small issues.

2022-11-15 20:42 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +auteur: 'Janet Schwartz & Khoa Lam'
The keys "titre" and "auteur" should still be in English – it doesn't work otherwise.

2022-11-15 20:42 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
>  ## 🦾 Support our Efforts
"Support our Efforts" is still in English.

2022-11-15 20:42 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +* **Qui était impliqué ?** [Glovo](/entities/glovo) a développé et déployé un système d'IA, qui a nui à [Sebastian Galassi](/entities/sebastian-galassi) et [à la famille de Sebastian Galassi](/entiti
The family link is broken and should not be translated. i.e. `[à la famille de Sebastian Galassi](/entities/sebastian-galassi's-family)`

2022-11-15 20:42 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +* En savoir plus sur les développeurs, les déployeurs et les parties lésées présumés dans [Entities Page](/entities)
I think "Table View" and "Entities Page" should probably be translated. "Entities" is currently untranslated in the sidebar, so perhaps we should try to synchronize them in this PR.

![image](https://user-images.githubusercontent.com/25443411/202018701-468309ac-01fe-46b8-9f7c-9b6d646fc650.png)

2022-11-15 20:42 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +* **Que s'est-il passé ?** Le haut-parleur Google Home Mini a été signalé par des utilisateurs pour avoir annoncé à haute voix le mot n précédemment censuré dans un titre de chanson. On ne sait pas q
Is there a reason why it's "le mot n" the first time and then "le n-word" the second time?

2022-11-16 15:47 UTC, clari182 commented
Definitely did that translation too fast, next time I'll double-check more!

2022-11-16 16:06 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +1. Partagez cette newsletter sur [LinkedIn](https://www.linkedin.com/company/responsible-ai-collaborative), [Twitter](https://twitter.com/IncidentsDB) et [Facebook](https ://www.facebook.com/Incident
There's an extra space in the Facebook link.

2022-11-16 16:07 UTC, lmcnulty commented on site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
> +    - **Biais et discrimination :** [#355](/cite/355), [#356](/cite/356), [#359](/cite/359), [#367](/cite/ 367), [#374](/cite/374), [#383](/cite/383/)
There's an extra space in `/cite/ 361` and `[#367](/cite/ 367)` that's causing those links not to work.
![image](https://user-images.githubusercontent.com/25443411/202231914-becfda0c-1a88-4128-930d-245e2a1922b9.png)

2022-11-16 16:15 UTC, lmcnulty commented
Thanks! I think those are the only two things. My [original PR](https://github.com/responsible-ai-collaborative/aiid/pull/1380) has been merged, so if possible I think you'll also need to either change the destination of this PR to upstream, or open a new PR with the same contents.

2024-02-01 19:55 UTC, closed without merging